# Generated by Django 5.2.10 on 2026-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_rename_duration_seconds_quiz_duration_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam'), ('Al-Ahsa', 'Al-Ahsa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('BUS', 'Business'), ('LS', 'Language Studies')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
