# Generated by Django 5.2.10 on 2026-02-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_question_question_type_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_answers', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice (4 options)'), ('true_false', 'True / False'), ('file_upload', 'File Upload (Student uploads file)')], default='multiple_choice', max_length=20),
        ),
    ]
