# Generated by Django 5.2.10 on 2026-04-25 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_add_submission_grading_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_topics', models.JSONField(blank=True, default=list, help_text='List of identified weak topics with explanations')),
                ('flashcards', models.JSONField(blank=True, default=list, help_text='Flashcards for revision on weak topics')),
                ('practice_questions', models.JSONField(blank=True, default=list, help_text='Generated practice questions with solutions')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the feedback was generated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('generation_error', models.TextField(blank=True, help_text='Error message if feedback generation failed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the student first viewed this feedback', null=True)),
                ('submission', models.OneToOneField(help_text='The quiz submission this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='quizzes.submission')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
